### ISSUE TITLE
NoMethodError (undefined method `decode' for URI:Module):    lib/rescued_tenant_elevator.rb:10:in `block in call' lib/rescued_tenant_elevator.rb:10:in `call' on ruby 3.0.0

### ISSUE THREAD

**Issue by AlbiTabaku** [rails-on-services/apartment#202]
## Steps to reproduce
move from ruby 2.7.4 to 3.0.0
## Expected behavior
Should switch correctly to tenants
## Actual behavior
Cannot switch to tenant, problem in the generic.rb file on @app.call(env)  undefined method `decode' for URI:Module)
## System configuration

* Database: (Tell us what database and its version you use.)

* Apartment version:
2.11.0
* Apartment config (in `config/initializers/apartment.rb` or so):
require 'apartment/elevators/subdomain'

class RescuedTenantElevator < ::Apartment::Elevators::Subdomain
  def call(env)
    super
  rescue Apartment::TenantNotFound
    [302, { 'Content-Type' => 'text/hml', 'Location' => Rails.application.routes.url_helpers.root_url }, self]
  end

  # needed to work
  def each
  end
end
  * `use_schemas`: (`true` or `false`)

* Rails (or ActiveRecord) version:
6.0.4.1
* Ruby version:
3.0.0

**Comment by AlbiTabaku** [comment]
https://stackoverflow.com/questions/72183528/using-ros-apartment-gem-with-ruby-3-0-0
