### ISSUE TITLE
action_mailer/railtie

### ISSUE THREAD

**Issue by m-zielinski** [rails-on-services/apartment#285]
## Steps to reproduce
* setup everything according to the README
* `bundle exec rake spec`

## Expected behavior
all test pass

## Actual behavior
multiple
```
LoadError:
  cannot load such file -- action_mailer/railtie
# ./spec/dummy/config/application.rb:9:in `<top (required)>'
# ./spec/dummy/config/environment.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:8:in `<top (required)>'
```

## System configuration

* Database: (Tell us what database and its version you use.)

* Apartment version:

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: (`true` or `false`)

* Rails (or ActiveRecord) version:

* Ruby version:

**Comment by m-zielinski** [comment]
`bundle exec appraisal rake spec` is the correct command to run all the tests
